<?php
/**
 * GateWey Requisition Management System
 * Excel Exporter Class
 * 
 * File: classes/ExcelExporter.php
 * Purpose: Export reports to Excel format using PHPSpreadsheet
 * 
 * Note: Requires PHPSpreadsheet library
 * Install: composer require phpoffice/phpspreadsheet
 */

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;

class ExcelExporter {
    
    private $spreadsheet;
    private $worksheet;
    
    /**
     * Constructor
     */
    public function __construct() {
        $this->spreadsheet = new Spreadsheet();
        $this->worksheet = $this->spreadsheet->getActiveSheet();
    }
    
    /**
     * Export requisition report to Excel
     * 
     * @param array $data Export data from Report class
     * @param string $reportType Report type (personal, department, organization)
     * @return bool Success status
     */
    public function exportReport($data, $reportType = 'personal') {
        try {
            // Set metadata
            $this->setMetadata($reportType);
            
            // Add summary sheet
            $this->addSummarySheet($data, $reportType);
            
            // Add detailed data sheet
            $this->addDataSheet($data, $reportType);
            
            // Generate filename
            $filename = $this->generateFilename($reportType);
            
            // Set headers for download
            $this->setDownloadHeaders($filename);
            
            // Output file
            $writer = new Xlsx($this->spreadsheet);
            $writer->save('php://output');
            
            return true;
            
        } catch (Exception $e) {
            error_log("Excel export error: " . $e->getMessage());
            return false;
        }
    }
    
    /**
     * Set Excel metadata
     * 
     * @param string $reportType Report type
     */
    private function setMetadata($reportType) {
        $this->spreadsheet->getProperties()
            ->setCreator('GateWey Requisition System')
            ->setTitle(ucfirst($reportType) . ' Requisition Report')
            ->setSubject('Requisition Report')
            ->setDescription('Generated requisition report from GateWey system');
    }
    
    /**
     * Add summary sheet
     * 
     * @param array $data Export data
     * @param string $reportType Report type
     */
    private function addSummarySheet($data, $reportType) {
        $sheet = $this->spreadsheet->getActiveSheet();
        $sheet->setTitle('Summary');
        
        $stats = $data['statistics'];
        $filters = $data['filters'];
        
        // Title
        $sheet->setCellValue('A1', 'GATEWEY REQUISITION REPORT');
        $sheet->mergeCells('A1:D1');
        $sheet->getStyle('A1')->getFont()->setSize(16)->setBold(true);
        $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        
        // Report Info
        $row = 3;
        $sheet->setCellValue('A' . $row, 'Report Type:');
        $sheet->setCellValue('B' . $row, ucfirst($reportType) . ' Report');
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        
        $row++;
        $sheet->setCellValue('A' . $row, 'Generated:');
        $sheet->setCellValue('B' . $row, date('Y-m-d H:i:s'));
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        
        $row++;
        $sheet->setCellValue('A' . $row, 'Generated By:');
        $sheet->setCellValue('B' . $row, $data['generated_by']);
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        
        // Filters Applied
        $row += 2;
        $sheet->setCellValue('A' . $row, 'FILTERS APPLIED');
        $sheet->mergeCells('A' . $row . ':D' . $row);
        $sheet->getStyle('A' . $row)->getFont()->setBold(true)->setSize(12);
        $sheet->getStyle('A' . $row)->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()->setRGB('E2E8F0');
        
        $row++;
        if (!empty($filters['period'])) {
            $sheet->setCellValue('A' . $row, 'Period:');
            $sheet->setCellValue('B' . $row, ucfirst($filters['period']));
            $sheet->getStyle('A' . $row)->getFont()->setBold(true);
            $row++;
        }
        
        if (!empty($filters['date_from']) || !empty($filters['date_to'])) {
            $sheet->setCellValue('A' . $row, 'Date Range:');
            $dateRange = ($filters['date_from'] ?? 'Any') . ' to ' . ($filters['date_to'] ?? 'Any');
            $sheet->setCellValue('B' . $row, $dateRange);
            $sheet->getStyle('A' . $row)->getFont()->setBold(true);
            $row++;
        }
        
        if (!empty($filters['status'])) {
            $sheet->setCellValue('A' . $row, 'Status:');
            $sheet->setCellValue('B' . $row, get_status_text($filters['status']));
            $sheet->getStyle('A' . $row)->getFont()->setBold(true);
            $row++;
        }
        
        // Statistics
        $row += 2;
        $sheet->setCellValue('A' . $row, 'STATISTICS');
        $sheet->mergeCells('A' . $row . ':D' . $row);
        $sheet->getStyle('A' . $row)->getFont()->setBold(true)->setSize(12);
        $sheet->getStyle('A' . $row)->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()->setRGB('E2E8F0');
        
        $row++;
        $sheet->setCellValue('A' . $row, 'Total Requisitions:');
        $sheet->setCellValue('B' . $row, number_format($stats['total_count']));
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        
        $row++;
        $sheet->setCellValue('A' . $row, 'Total Amount:');
        $sheet->setCellValue('B' . $row, $stats['total_amount']);
        $sheet->getStyle('B' . $row)->getNumberFormat()
            ->setFormatCode(NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        
        $row++;
        $sheet->setCellValue('A' . $row, 'Average Amount:');
        $sheet->setCellValue('B' . $row, $stats['average_amount']);
        $sheet->getStyle('B' . $row)->getNumberFormat()
            ->setFormatCode(NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        
        $row++;
        $sheet->setCellValue('A' . $row, 'Minimum Amount:');
        $sheet->setCellValue('B' . $row, $stats['min_amount']);
        $sheet->getStyle('B' . $row)->getNumberFormat()
            ->setFormatCode(NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        
        $row++;
        $sheet->setCellValue('A' . $row, 'Maximum Amount:');
        $sheet->setCellValue('B' . $row, $stats['max_amount']);
        $sheet->getStyle('B' . $row)->getNumberFormat()
            ->setFormatCode(NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        
        // Status Breakdown
        if (!empty($stats['status_breakdown'])) {
            $row += 2;
            $sheet->setCellValue('A' . $row, 'STATUS BREAKDOWN');
            $sheet->mergeCells('A' . $row . ':D' . $row);
            $sheet->getStyle('A' . $row)->getFont()->setBold(true)->setSize(12);
            $sheet->getStyle('A' . $row)->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()->setRGB('E2E8F0');
            
            $row++;
            $sheet->setCellValue('A' . $row, 'Status');
            $sheet->setCellValue('B' . $row, 'Count');
            $sheet->setCellValue('C' . $row, 'Total Amount');
            $sheet->getStyle('A' . $row . ':C' . $row)->getFont()->setBold(true);
            $sheet->getStyle('A' . $row . ':C' . $row)->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()->setRGB('CBD5E1');
            
            foreach ($stats['status_breakdown'] as $statusData) {
                $row++;
                $sheet->setCellValue('A' . $row, get_status_text($statusData['status']));
                $sheet->setCellValue('B' . $row, number_format($statusData['count']));
                $sheet->setCellValue('C' . $row, $statusData['total']);
                $sheet->getStyle('C' . $row)->getNumberFormat()
                    ->setFormatCode(NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);
            }
        }
        
        // Auto-size columns
        $sheet->getColumnDimension('A')->setWidth(20);
        $sheet->getColumnDimension('B')->setWidth(25);
        $sheet->getColumnDimension('C')->setWidth(20);
        $sheet->getColumnDimension('D')->setWidth(20);
    }
    
    /**
     * Add detailed data sheet
     * 
     * @param array $data Export data
     * @param string $reportType Report type
     */
    private function addDataSheet($data, $reportType) {
        // Create new worksheet for data
        $sheet = $this->spreadsheet->createSheet();
        $sheet->setTitle('Requisitions');
        
        $requisitions = $data['requisitions'];
        
        // Headers
        $headers = [
            'A1' => 'Requisition No.',
            'B1' => 'Date Created',
            'C1' => 'Requester',
            'D1' => 'Department',
            'E1' => 'Purpose',
            'F1' => 'Amount',
            'G1' => 'Status',
            'H1' => 'Submitted Date',
            'I1' => 'Payment Date',
            'J1' => 'Completed Date'
        ];
        
        foreach ($headers as $cell => $header) {
            $sheet->setCellValue($cell, $header);
        }
        
        // Style headers
        $sheet->getStyle('A1:J1')->getFont()->setBold(true);
        $sheet->getStyle('A1:J1')->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()->setRGB('4A5568');
        $sheet->getStyle('A1:J1')->getFont()->getColor()->setRGB('FFFFFF');
        $sheet->getStyle('A1:J1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        
        // Add data rows
        $row = 2;
        foreach ($requisitions as $req) {
            $requesterName = ($req['requester_first_name'] ?? '') . ' ' . ($req['requester_last_name'] ?? '');
            if (empty(trim($requesterName))) {
                $requesterName = 'Self'; // For personal reports
            }
            
            $sheet->setCellValue('A' . $row, $req['requisition_number']);
            $sheet->setCellValue('B' . $row, $req['created_at']);
            $sheet->setCellValue('C' . $row, $requesterName);
            $sheet->setCellValue('D' . $row, $req['department_name'] ?? 'N/A');
            $sheet->setCellValue('E' . $row, $req['purpose']);
            $sheet->setCellValue('F' . $row, $req['total_amount']);
            $sheet->setCellValue('G' . $row, get_status_text($req['status']));
            $sheet->setCellValue('H' . $row, $req['submitted_at'] ?? 'N/A');
            $sheet->setCellValue('I' . $row, $req['paid_at'] ?? 'N/A');
            $sheet->setCellValue('J' . $row, $req['receipt_uploaded_at'] ?? 'N/A');
            
            // Format amount
            $sheet->getStyle('F' . $row)->getNumberFormat()
                ->setFormatCode(NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);
            
            // Alternate row colors
            if ($row % 2 == 0) {
                $sheet->getStyle('A' . $row . ':J' . $row)->getFill()
                    ->setFillType(Fill::FILL_SOLID)
                    ->getStartColor()->setRGB('F7FAFC');
            }
            
            $row++;
        }
        
        // Add borders
        $lastRow = $row - 1;
        $sheet->getStyle('A1:J' . $lastRow)->getBorders()->getAllBorders()
            ->setBorderStyle(Border::BORDER_THIN)
            ->getColor()->setRGB('CBD5E1');
        
        // Auto-size columns
        foreach (range('A', 'J') as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
        }
        
        // Freeze header row
        $sheet->freezePane('A2');
    }
    
    /**
     * Generate filename
     * 
     * @param string $reportType Report type
     * @return string Filename
     */
    private function generateFilename($reportType) {
        $date = date('Y-m-d_His');
        return "GateWey_{$reportType}_Report_{$date}.xlsx";
    }
    
    /**
     * Set download headers
     * 
     * @param string $filename Filename
     */
    private function setDownloadHeaders($filename) {
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="' . $filename . '"');
        header('Cache-Control: max-age=0');
        header('Cache-Control: max-age=1');
        header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
        header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT');
        header('Cache-Control: cache, must-revalidate');
        header('Pragma: public');
    }
}